sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t akhil1996261/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akhil1996261/docker-react npm run test
